#!/bin/sh
# 
# A userscript for Emacs interface to Web-based chat (e.g., ChatGPT).
# Copyright (c) 2023, Hiroyuki Ohsaki.
# All rights reserved.
# 

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Parse command line options.
while getopts 's:r:' var
do
    case "$var" in
	s)
	    mode=send
	    file=$OPTARG
	    ;;
	r)
	    mode=recv
	    file=$OPTARG
	    ;;
    esac
done
shift `expr $OPTIND - 1`

# FIXME: Avoid hard-coding.
# FIXME: This file must be unreadable by others.
tmpfile=/tmp/chat-proxy.tmp

case "$mode" in
    send)
	# Save all the text content.
	cp $QUTE_TEXT $tmpfile
	# Fill the form with the query text stored in $FILE.
	echo 'mode-enter insert' >>$QUTE_FIFO
	echo "insert-text `cat $file`" >>$QUTE_FIFO
	sleep .1
	# Press the entry key in qutebrowser.
	echo 'fake-key <Enter>' >>$QUTE_FIFO
	;;
    recv)
	# Detect the newly-generated texts.
	# 1. Remove the first three lines.
	# 2. Pick lines starting with '+'.
	# e. Remove '+' at the beginning of line.
	# FIXME: Output in Markdown rather than plain text.
	diff -u $tmpfile $QUTE_TEXT | \
	    sed -n '4,$p' | sed -n '/^+/p' | sed 's/^+//' >$file
	;;
esac

exit 0
